UdK-VPT/BuildingSystems

BuildingSystems/Buildings/Airvolumes/Airvolume3D.mo
BuildingSystems/Buildings/Airvolumes/AirvolumeCompressible0D.mo
BuildingSystems/Buildings/BaseClasses/ConstructionGeneral.mo
BuildingSystems/Buildings/Examples/ThermalModelHouse3Dwindow.mo
BuildingSystems/HAM/ConvectiveHeatTransfer/Gaps/package.mo
BuildingSystems/HAM/HeatRadiation/BaseClasses/HeatRadiationTwoSurfaces.mo
BuildingSystems/Technologies/Photovoltaics/Data/PhotovoltaicModules.mo
BuildingSystems/Utilities/MoistAirFunctions/T_dp.mo
BuildingSystems/Utilities/MoistAirFunctions/T_sat.mo
BuildingSystems/Utilities/MoistAirFunctions/enthalpy.mo
BuildingSystems/Utilities/MoistAirFunctions/p.mo

Issue2_GermanComments

---

.gitignore

ignore temporary files created by diff and merge tool

---

BuildingSystems/Buildings/Airvolumes/Airvolume3D.mo
BuildingSystems/Types/WaterVapourEnthalpy.mo

This should fix #15.
Additonally removed superfluous unit declaration.

Issue15_WaterVapourEnthalpy

---

BuildingSystems/Applications/ClimateAnalyses/FreeFloatingTemperature.mo
BuildingSystems/HAM/HeatAndMoistureTransport/Examples/HeatAndMoistureTransport1DNodes.mo
BuildingSystems/HAM/HeatAndMoistureTransport/Examples/HeatAndMoistureTransport3D.mo

issue26_NumberOfIntervals

---

BuildingSystems/Utilities/NcDataReader2/NcDataReader.mo

Issue17 nc data reader

---

BuildingSystems/Buildings/Airvolumes/Airvolume3D.mo
BuildingSystems/Buildings/Examples/ThermalModelHouse3D.mo
BuildingSystems/Buildings/Zones/ZoneTemplateAirvolume3D.mo

Removal of zone3D_visualization code

Removal of zone3D_visualization code

---

BuildingSystems/Buildings/Airvolumes/Airvolume3D.mo
BuildingSystems/Buildings/Zones/ZoneTemplateAirvolume3D.mo

Update of some of the zonal3D components, basic error (dymola check fails, translate/simulate works fine) still occurs.

Update of 3D components

---

BuildingSystems/Buildings/Airvolumes/Airvolume3D.mo

Small adjustments of the zonal3D code to match UCaHS/AirVolumes3Dv23alpha

commenting and small adjustments

---

BuildingSystems/Controls/Continuous/LimPID.mo
BuildingSystems/HAM/HeatConduction/HeatConduction1D.mo
BuildingSystems/HAM/HeatConduction/HeatConduction3D.mo

this will close #44 for now.
Remaining warnings are in the Modelica License

Issue44 html

---

BuildingSystems/HAM/HeatConduction/HeatConduction3D.mo

this is for #7
See Modelica Specification section 19.1:
The unit of measure of a dimension free quantity is denoted by "1".
https://www.modelica.org/documents/ModelicaSpec33Revision1.pdf#page=245

dimensionless factor

---

BuildingSystems/Buildings/BaseClasses/HeatConduction3DWithTube.mo
BuildingSystems/Fluid/FixedResistances/LosslessPipe.mo
BuildingSystems/Fluid/FixedResistances/Pipe.mo

OpenModelica was complaining about 256 being out of range

RGB is in the range 0...255

---

BuildingSystems/HAM/HeatConduction/BaseClasses/HeatConductionGeneral.mo
BuildingSystems/HAM/HeatConduction/Examples/HeatConduction1DNodes.mo
BuildingSystems/HAM/HeatConduction/Examples/package.order
BuildingSystems/HAM/HeatConduction/HeatConduction1DNodes.mo
BuildingSystems/HAM/HeatConduction/MultiLayerHeatConduction1DNodes.mo

Can we merge this into the master as it is, right now?
Then it will get tested by the OpenModelica CI.
After merging we can keep the branch (or create a new one) to work on possible fixes.

Issue88 wall

---

BuildingSystems/Technologies/DistrictHeatingNetworks/EnergyProductionUnits/Central.mo

remove annotation experiment

---

BuildingSystems/Technologies/ThermalStorages/FluidStorage.mo

this closes #89 
All four FluidStorage examples then also work in OpenModelica (with some warnings).

use nEle as used in declaration

---

BuildingSystems/Technologies/SolarThermal/ThermalCollector.mo
BuildingSystems/Technologies/SolarThermal/ThermalCollectorInSeries.mo

this closes #94 
but probably someone should review the whole ThermalCollector model!?

Issue94 connect thermal

---

BuildingSystems/Applications/HeatingSystems/SolarHeatingSystem.mo
BuildingSystems/Applications/HeatingSystems/WaterHeatingSystem.mo
BuildingSystems/Applications/SolarThermalSystems/SolarThermalSystem1.mo
BuildingSystems/Applications/SolarThermalSystems/SolarThermalSystem2.mo
BuildingSystems/Buildings/BuildingTemplates/Building1Zone0D.mo
BuildingSystems/Technologies/DistrictHeatingNetworks/Examples/DistrictHeatingNetwork_dp.mo
BuildingSystems/Technologies/DistrictHeatingNetworks/Examples/DistrictHeatingNetwork_m_flow.mo

using a conversion script as described in #98 
Opening the PR, so the changes are easily visible,
but more work is needed as the examples still do not work

rename HeaterCooler_T to PrescribedOutlet

---

BuildingSystems/Buildings/Ambient.mo
BuildingSystems/Technologies/ElectricalStorages/BatterySimple.mo

https://github.com/lbl-srg/BuildingsPy/issues/52
https://github.com/htacg/tidy-html5/issues/521

fix <li></li>

---

BuildingSystems/Applications/DistrictSimulation/HCBC.mo
BuildingSystems/Buildings/BaseClasses/ZoneTemplateGeneral.mo
BuildingSystems/Buildings/BuildingTemplates/Building1Zone0D.mo
BuildingSystems/Buildings/BuildingTemplates/Building1Zone1DBox.mo
BuildingSystems/Buildings/BuildingTemplates/Building1Zone1DCylinder.mo
BuildingSystems/Buildings/Constructions/Examples/Door.mo
BuildingSystems/Buildings/Constructions/Examples/SlidingWindow.mo
BuildingSystems/Buildings/Constructions/Examples/WindowWithAirpathes.mo
BuildingSystems/Buildings/Examples/BuildingHygroThermal1Zone1D.mo
BuildingSystems/Buildings/Examples/BuildingThermal1Zone1D.mo
BuildingSystems/Buildings/Examples/BuildingThermal4Zones1D.mo
BuildingSystems/Buildings/Examples/BuildingThermalMultiZone.mo
BuildingSystems/Buildings/Interfaces/SurfaceToAirPortGeneral.mo
BuildingSystems/Buildings/Interfaces/SurfaceToConstructionPortGeneral.mo
BuildingSystems/Buildings/Interfaces/SurfaceToConstructionPorts.mo
BuildingSystems/Buildings/Interfaces/SurfaceToSurfacesPortGeneral.mo
BuildingSystems/Buildings/Surfaces/SurfacesToAir.mo
BuildingSystems/Buildings/Surfaces/SurfacesToSolids.mo
BuildingSystems/Buildings/Zones/Examples/SingleZoneHygroThermal1D.mo
BuildingSystems/Buildings/Zones/Examples/SingleZoneThermal1D.mo
BuildingSystems/Buildings/Zones/ZoneTemplateAirvolumeMixed.mo
BuildingSystems/Resources/Documentation/ExamplesUserGuide/ThermalModelHouse.mo
BuildingSystems/Resources/Scripts/Dymola/Buildings/Examples/BuildingThermal4Zones1D.mos

Simplified zone model with only one interface for the building constructions introduced

N constructions

---

BuildingSystems/Buildings/Interfaces/AirpathPorts.mo

One small change regarding the description of AirpathPorts

AirpathPorts.mo: Changed description

---

docs/source/introduction.rst
docs/source/multiZoneModelling.rst

this is my branch for working on the docs, see #117

WIP: update docs

---

BuildingSystems/Resources/Scripts/Dymola/Technologies/ElectricalStorages/Examples/BatteryComplex.mos
BuildingSystems/Technologies/ElectricalStorages/BaseClasses/Battery.mo
BuildingSystems/Technologies/ElectricalStorages/BaseClasses/package.mo
BuildingSystems/Technologies/ElectricalStorages/BaseClasses/package.order
BuildingSystems/Technologies/ElectricalStorages/BatteryComplex.mo
BuildingSystems/Technologies/ElectricalStorages/BatterySimple.mo
BuildingSystems/Technologies/ElectricalStorages/Data/BaseClasses/ElectricBatteryGeneral.mo
BuildingSystems/Technologies/ElectricalStorages/Data/BaseClasses/package.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LeadAcid/Chloride200Ah.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LeadAcid/LeadAcidGeneric.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LeadAcid/Long7Ah.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LeadAcid/package.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LeadAcid/package.order
BuildingSystems/Technologies/ElectricalStorages/Data/LithiumIon/LithiumIonAquion.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LithiumIon/LithiumIonTeslaPowerwall1.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LithiumIon/LithiumIonTeslaPowerwall2.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LithiumIon/LithiumIonViessmann.mo
BuildingSystems/Technologies/ElectricalStorages/Data/LithiumIon/package.mo
BuildingSystems/Technologies/ElectricalStorages/Data/package.mo
BuildingSystems/Technologies/ElectricalStorages/Examples/BatteryComplex.mo
BuildingSystems/Technologies/ElectricalStorages/Examples/BatterySimple.mo
BuildingSystems/Technologies/ElectricalStorages/Examples/package.mo
BuildingSystems/Technologies/ElectricalStorages/Examples/package.order
BuildingSystems/Technologies/ElectricalStorages/package.mo
BuildingSystems/Technologies/ElectricalStorages/package.order

new BaseClasses.Battery as partial model for BatterySimple and BatteryComplex
added 2 data sets for Lead Acid batteries and 
added new parameter p ("Peukert Coefficient") to calculate variable capacity at various loads
added a_mcr (maximum charge rate) to reduce charge rate at 80% SOC

Issue122 battery model

---

BuildingSystems/Resources/Scripts/JModelica/Applications/HeatingSystems/SolarHeatingSystem.py

use environment variable set by JModelica,
proper indentation,
and use codecells so that the script can be run in one piece, or step by step (at least in spyder)
https://pythonhosted.org/spyder/editor.html#how-to-define-a-code-cell
https://donjayamanne.github.io/pythonVSCodeDocs/docs/jupyter_getting-started/#Defining-a-cell

os.environ['JMODELICA_HOME']

---

docs/source/multiZoneModelling.rst

wrong description in docs\source\multiZoneModelling.rst corrected

wrong description in docs\source\multiZoneModelling.rst corrected

---

BuildingSystems/Technologies/DistrictHeatingNetworks/BoundaryConditions/GroundTemperature0D.mo

Issue137 ground temperature

---

BuildingSystems/Utilities/SmoothFunctions/softcut.mo
BuildingSystems/Utilities/SmoothFunctions/softcut_lower.mo
BuildingSystems/Utilities/SmoothFunctions/softcut_upper.mo

see #101 and https://github.com/ibpsa/modelica-ibpsa/issues/169

refactor softcut_lower aka softmax
